In [56]:
import pandas as pd
import numpy as np
import csv

In [57]:
marks = pd.Series([12,31,43,53,11])
print(marks)

0    12
1    31
2    43
3    53
4    11
dtype: int64

In [58]:
print(marks[1])

31

In [59]:
# Labels

marks = pd.Series([80,90,75],
                  index = ["eev","ana",'sanj']
                  )
print(marks)

eev     80
ana     90
sanj    75
dtype: int64

In [60]:
print(marks["sanj"])

75

In [61]:
# Creating data frame

data = {
    "Name" : ["eev","ana","sanj"],
    "Marks" : [85,89,90],
    "age" : [21,21,21]
}
df = pd.DataFrame(data)
df.head()

   Name  Marks  age
0   eev     85   21
1   ana     89   21
2  sanj     90   21

In [62]:
df.shape

(3, 3)

In [63]:
df.columns

Index(['Name', 'Marks', 'age'], dtype='object')

In [64]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      object
 1   Marks   3 non-null      int64
 2   age     3 non-null      int64
dtypes: int64(2), object(1)
memory usage: 204.0+ bytes

In [65]:
df.describe()

           Marks   age
count   3.000000   3.0
mean   88.000000  21.0
std     2.645751   0.0
min    85.000000  21.0
25%    87.000000  21.0
50%    89.000000  21.0
75%    89.500000  21.0
max    90.000000  21.0

In [66]:
df.tail()

   Name  Marks  age
0   eev     85   21
1   ana     89   21
2  sanj     90   21

In [67]:
df.tail(2)

   Name  Marks  age
1   ana     89   21
2  sanj     90   21

In [68]:
df.tail(-2)

   Name  Marks  age
2  sanj     90   21

In [69]:
df["Name"]

0     eev
1     ana
2    sanj
Name: Name, dtype: object

In [70]:
df["Marks"]

0    85
1    89
2    90
Name: Marks, dtype: int64

In [71]:
df.age

0    21
1    21
2    21
Name: age, dtype: int64

In [72]:
df["age"]

0    21
1    21
2    21
Name: age, dtype: int64

In [73]:
df[["Name","Marks"]]

   Name  Marks
0   eev     85
1   ana     89
2  sanj     90

In [74]:
df.loc[0]

Name     eev
Marks     85
age       21
Name: 0, dtype: object

In [75]:
df.iloc[1]

Name     ana
Marks     89
age       21
Name: 1, dtype: object

In [76]:
df.iloc[2]

Name     sanj
Marks      90
age        21
Name: 2, dtype: object

In [77]:
df.loc[2]

Name     sanj
Marks      90
age        21
Name: 2, dtype: object

In [78]:
df.iloc[1:3,0:2]

   Name  Marks
1   ana     89
2  sanj     90

In [79]:
result = df[
    (df["Marks"] > 80) & (df["age"] < 22)
]

In [80]:
result

   Name  Marks  age
0   eev     85   21
1   ana     89   21
2  sanj     90   21

In [82]:
df2 = pd.read_csv('mercedesbenz.csv',usecols=['ID','y','X0','X1','X2'])
df2

        ID       y  X0 X1  X2
0        0  130.81   k  v  at
1        6   88.53   k  t  av
2        7   76.26  az  w   n
3        9   80.62  az  t   n
4       13   78.02  az  v   n
...    ...     ...  .. ..  ..
4204  8405  107.39  ak  s  as
4205  8406  108.77   j  o   t
4206  8412  109.22  ak  v   r
4207  8415   87.48  al  r   e
4208  8417  110.85   z  r  ae

[4209 rows x 5 columns]

In [83]:
df2.head()

   ID       y  X0 X1  X2
0   0  130.81   k  v  at
1   6   88.53   k  t  av
2   7   76.26  az  w   n
3   9   80.62  az  t   n
4  13   78.02  az  v   n

In [85]:
df2.to_csv('test.csv',index=False)

In [87]:
# Json: REAd json, to json, normalis
data = '{"name" : "abcde", "age" : 30}'
pd.read_json(data,orient='index')

C:\Users\prade\AppData\Local\Temp\ipykernel_38260\4195614148.py:3: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  pd.read_json(data,orient='index')

          0
name  abcde
age      30